FROM node:18

WORKDIR /app

# Clone the repository
RUN git clone https://github.com/get-convex/convex-backend.git .

# Install dependencies
WORKDIR /app/npm-packages/dashboard-self-hosted
RUN npm install -g @microsoft/rush
RUN rush update

EXPOSE 6791

#CMD NEXT_PUBLIC_DEPLOYMENT_URL=$NEXT_PUBLIC_DEPLOYMENT_URL rush build -t dashboard-self-hosted && npm start

CMD NEXT_PUBLIC_DEPLOYMENT_URL=$NEXT_PUBLIC_DEPLOYMENT_URL rush build -t dashboard-self-hosted && node .next/standalone/server.js
