version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    image: ghcr.io/get-convex/self-hosted-dashboard:latest
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${DEPLOYMENT_URL}
      - NEXT_PUBLIC_ADMIN_KEY=${ADMIN_KEY}
