version: "3"

services:
  backend:
    #image: ghcr.io/get-convex/self-hosted-backend:latest
    build:
      context: ..
      dockerfile: self-hosted/Dockerfile.backend
    ports:
      - "${PORT:-3210}:3210"
      - "${SITE_PROXY_PORT:-3211}:3211"
    volumes:
      - data:/convex/data
    environment:
      - PORT=${PORT:-3210}
      - SITE_PROXY_PORT=${SITE_PROXY_PORT:-3211}
      - INSTANCE_NAME=${INSTANCE_NAME}
      - INSTANCE_SECRET=${INSTANCE_SECRET}
      - CONVEX_RELEASE_VERSION_DEV=${CONVEX_RELEASE_VERSION_DEV}
      - ACTIONS_USER_TIMEOUT_SECS=${ACTIONS_USER_TIMEOUT_SECS}
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN}
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN}
    container_name: convex-local-backend
    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 5s
    labels:
      - "traefik.docker.network=ico4cswwkc0wko4ssoo8k4gk"
      - "traefik.http.routers.http-0-ico4cswwkc0wko4ssoo8k4gk-backend.service=service-0-ico4cswwkc0wko4ssoo8k4gk-backend"
      - "traefik.http.routers.http-1-ico4cswwkc0wko4ssoo8k4gk-backend.service=service-1-ico4cswwkc0wko4ssoo8k4gk-backend"
      - "traefik.http.routers.https-0-ico4cswwkc0wko4ssoo8k4gk-backend.service=service-0-ico4cswwkc0wko4ssoo8k4gk-backend"
      - "traefik.http.routers.https-1-ico4cswwkc0wko4ssoo8k4gk-backend.service=service-1-ico4cswwkc0wko4ssoo8k4gk-backend"
      - "traefik.http.services.service-0-ico4cswwkc0wko4ssoo8k4gk-backend.loadbalancer.server.port=3210"
      - "traefik.http.services.service-1-ico4cswwkc0wko4ssoo8k4gk-backend.loadbalancer.server.port=3211"     
      
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    image: ghcr.io/get-convex/self-hosted-dashboard:latest
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    environment:
      - DASHBOARD_PORT=${DASHBOARD_PORT:-6791}
      - NEXT_PUBLIC_DEPLOYMENT_URL=${CONVEX_SITE_ORIGIN}
    depends_on:
      backend:
        condition: service_healthy

volumes:
  data:
